[package]
name = "quickseg"
version = "1.0.0"
edition = "2024"

[dependencies]
quickseg-core = { path = "../quickseg-core" }
clap = { version = "4.6", features = ["derive"] }
flate2 = "1.1"
atoi = "3.1"
memchr = "2.8"

[dev-dependencies]
criterion = "0.8"
tempfile = "3"
rand = "0.10"
rand_distr = "0.6"

[[bench]]
name = "quickseg_runtime"
harness = false

[[bin]]
name = "quickseg"
path = "src/main.rs"

